Added oboarding task completion by Eugene
DataBytes-Organisation/Project-Echo pull request #623
Opened 2024-11-14 19:48 UTC by EugeneKoh0125

2024-11-16 01:27 UTC, minhD03 approved these changes

2024-11-24 15:10 UTC, regina-arissa requested changes

2024-11-24 15:10 UTC, regina-arissa commented on Tutorials/Engine team first Git Commit/introduction_to_audio_-___delete_this_and_add_your_initials_here-___ _ copy.ipynb
Please do not delete this file from main, thanks

2024-11-24 15:10 UTC, regina-arissa commented on EK.ipynb
please move this file to the designated folder

2024-11-24 15:10 UTC, regina-arissa commented on Tutorials/Engine team first Git Commit/.ipynb_checkpoints/EK-checkpoint.ipynb
I think this one should not be in this folder. I believe the change should only be 1 file

2024-12-13 07:50 UTC, closed without merging