Add onboarding tutorial folder and contents
DataBytes-Organisation/Project-Echo pull request #652
Opened 2024-12-12 03:55 UTC by RileyLive

Team Members: MAHA JOKHIO, EUGENE OU YI KOH and Riley Beckett

2024-12-12 04:22 UTC, regina-arissa commented on Tutorials/onboarding_tutorial/Intro to Audio/.ipynb_checkpoints/introduction_to_audio-checkpoint.ipynb
don't include checkpoints

2024-12-12 04:34 UTC, regina-arissa commented on Tutorials/onboarding_tutorial/Onboarding Task.ipynb
Such an amazing job guys! I believe this will be very useful for future students in navigating our project. I have one suggestion for the last part, which is "git add ." Although it is a common practice to stage all of your changes, I think it is still better to stage your files separately, because when you do git add ., you stage everything including the checkpoints and sometimes unnecessary files like some audio data and environment folders, which could clutter our repository and makes it harder for reviewers to see the changes. I suggest changing this part so that new students are used to staging their changes one by one.

2024-12-12 04:35 UTC, regina-arissa requested changes
Great work so far, but can you only push the necessary change only? I don't think you need to push all of the images, as they are included in the ipynb file already. I also added some comments for you.

2024-12-13 04:02 UTC, RileyLive commented on Tutorials/onboarding_tutorial/Intro to Audio/.ipynb_checkpoints/introduction_to_audio-checkpoint.ipynb
The changes are updated

2025-01-12 17:15 UTC, mahajokhio2 commented
Closing pull request due to minor changes required which were submitted by another team member of this task in a different pull request which has now been merged.

2025-01-12 17:15 UTC, closed without merging